// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.awar.ags.net.protocol;

public final class Protocol
{
    private Protocol()
    {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry )
    {
    }

    public interface ProtocolMSGOrBuilder
            extends com.google.protobuf.MessageOrBuilder
    {

        // optional .com.awar.ags.net.protocol.LoginRequest loginrequest = 3;
        boolean hasLoginrequest();

        com.awar.ags.net.protocol.Protocol.LoginRequest getLoginrequest();

        com.awar.ags.net.protocol.Protocol.LoginRequestOrBuilder getLoginrequestOrBuilder();

        // optional .com.awar.ags.net.protocol.LoginResponse loginresponse = 4;
        boolean hasLoginresponse();

        com.awar.ags.net.protocol.Protocol.LoginResponse getLoginresponse();

        com.awar.ags.net.protocol.Protocol.LoginResponseOrBuilder getLoginresponseOrBuilder();
    }

    public static final class ProtocolMSG extends
            com.google.protobuf.GeneratedMessage
            implements ProtocolMSGOrBuilder
    {
        // Use ProtocolMSG.newBuilder() to construct.
        private ProtocolMSG( Builder builder )
        {
            super( builder );
        }

        private ProtocolMSG( boolean noInit )
        {
        }

        private static final ProtocolMSG defaultInstance;

        public static ProtocolMSG getDefaultInstance()
        {
            return defaultInstance;
        }

        public ProtocolMSG getDefaultInstanceForType()
        {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_ProtocolMSG_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_ProtocolMSG_fieldAccessorTable;
        }

        private int bitField0_;
        // optional .com.awar.ags.net.protocol.LoginRequest loginrequest = 3;
        public static final int LOGINREQUEST_FIELD_NUMBER = 3;
        private com.awar.ags.net.protocol.Protocol.LoginRequest loginrequest_;

        public boolean hasLoginrequest()
        {
            return ( ( bitField0_ & 0x00000001 ) == 0x00000001 );
        }

        public com.awar.ags.net.protocol.Protocol.LoginRequest getLoginrequest()
        {
            return loginrequest_;
        }

        public com.awar.ags.net.protocol.Protocol.LoginRequestOrBuilder getLoginrequestOrBuilder()
        {
            return loginrequest_;
        }

        // optional .com.awar.ags.net.protocol.LoginResponse loginresponse = 4;
        public static final int LOGINRESPONSE_FIELD_NUMBER = 4;
        private com.awar.ags.net.protocol.Protocol.LoginResponse loginresponse_;

        public boolean hasLoginresponse()
        {
            return ( ( bitField0_ & 0x00000002 ) == 0x00000002 );
        }

        public com.awar.ags.net.protocol.Protocol.LoginResponse getLoginresponse()
        {
            return loginresponse_;
        }

        public com.awar.ags.net.protocol.Protocol.LoginResponseOrBuilder getLoginresponseOrBuilder()
        {
            return loginresponse_;
        }

        private void initFields()
        {
            loginrequest_ = com.awar.ags.net.protocol.Protocol.LoginRequest.getDefaultInstance();
            loginresponse_ = com.awar.ags.net.protocol.Protocol.LoginResponse.getDefaultInstance();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if( isInitialized != -1 )
            {
                return isInitialized == 1;
            }

            if( hasLoginrequest() )
            {
                if( !getLoginrequest().isInitialized() )
                {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            if( hasLoginresponse() )
            {
                if( !getLoginresponse().isInitialized() )
                {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo( com.google.protobuf.CodedOutputStream output )
                throws java.io.IOException
        {
            getSerializedSize();
            if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) )
            {
                output.writeMessage( 3, loginrequest_ );
            }
            if( ( ( bitField0_ & 0x00000002 ) == 0x00000002 ) )
            {
                output.writeMessage( 4, loginresponse_ );
            }
            getUnknownFields().writeTo( output );
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize()
        {
            int size = memoizedSerializedSize;
            if( size != -1 )
            {
                return size;
            }

            size = 0;
            if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) )
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize( 3, loginrequest_ );
            }
            if( ( ( bitField0_ & 0x00000002 ) == 0x00000002 ) )
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize( 4, loginresponse_ );
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException
        {
            return super.writeReplace();
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseFrom(
                com.google.protobuf.ByteString data )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseFrom( byte[] data )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseFrom( java.io.InputStream input )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseDelimitedFrom( java.io.InputStream input )
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if( builder.mergeDelimitedFrom( input ) )
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if( builder.mergeDelimitedFrom( input, extensionRegistry ) )
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseFrom(
                com.google.protobuf.CodedInputStream input )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.ProtocolMSG parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry )
                    .buildParsed();
        }

        public static Builder newBuilder()
        {
            return Builder.create();
        }

        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public static Builder newBuilder( com.awar.ags.net.protocol.Protocol.ProtocolMSG prototype )
        {
            return newBuilder().mergeFrom( prototype );
        }

        public Builder toBuilder()
        {
            return newBuilder( this );
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent )
        {
            Builder builder = new Builder( parent );
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.awar.ags.net.protocol.Protocol.ProtocolMSGOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_ProtocolMSG_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_ProtocolMSG_fieldAccessorTable;
            }

            // Construct using com.awar.ags.net.protocol.Protocol.ProtocolMSG.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder( BuilderParent parent )
            {
                super( parent );
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization()
            {
                if( com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders )
                {
                    getLoginrequestFieldBuilder();
                    getLoginresponseFieldBuilder();
                }
            }

            private static Builder create()
            {
                return new Builder();
            }

            public Builder clear()
            {
                super.clear();
                if( loginrequestBuilder_ == null )
                {
                    loginrequest_ = com.awar.ags.net.protocol.Protocol.LoginRequest.getDefaultInstance();
                }
                else
                {
                    loginrequestBuilder_.clear();
                }
                bitField0_ = ( bitField0_ & ~0x00000001 );
                if( loginresponseBuilder_ == null )
                {
                    loginresponse_ = com.awar.ags.net.protocol.Protocol.LoginResponse.getDefaultInstance();
                }
                else
                {
                    loginresponseBuilder_.clear();
                }
                bitField0_ = ( bitField0_ & ~0x00000002 );
                return this;
            }

            public Builder clone()
            {
                return create().mergeFrom( buildPartial() );
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return com.awar.ags.net.protocol.Protocol.ProtocolMSG.getDescriptor();
            }

            public com.awar.ags.net.protocol.Protocol.ProtocolMSG getDefaultInstanceForType()
            {
                return com.awar.ags.net.protocol.Protocol.ProtocolMSG.getDefaultInstance();
            }

            public com.awar.ags.net.protocol.Protocol.ProtocolMSG build()
            {
                com.awar.ags.net.protocol.Protocol.ProtocolMSG result = buildPartial();
                if( !result.isInitialized() )
                {
                    throw newUninitializedMessageException( result );
                }
                return result;
            }

            private com.awar.ags.net.protocol.Protocol.ProtocolMSG buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                com.awar.ags.net.protocol.Protocol.ProtocolMSG result = buildPartial();
                if( !result.isInitialized() )
                {
                    throw newUninitializedMessageException(
                            result ).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.awar.ags.net.protocol.Protocol.ProtocolMSG buildPartial()
            {
                com.awar.ags.net.protocol.Protocol.ProtocolMSG result = new com.awar.ags.net.protocol.Protocol.ProtocolMSG( this );
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if( ( ( from_bitField0_ & 0x00000001 ) == 0x00000001 ) )
                {
                    to_bitField0_ |= 0x00000001;
                }
                if( loginrequestBuilder_ == null )
                {
                    result.loginrequest_ = loginrequest_;
                }
                else
                {
                    result.loginrequest_ = loginrequestBuilder_.build();
                }
                if( ( ( from_bitField0_ & 0x00000002 ) == 0x00000002 ) )
                {
                    to_bitField0_ |= 0x00000002;
                }
                if( loginresponseBuilder_ == null )
                {
                    result.loginresponse_ = loginresponse_;
                }
                else
                {
                    result.loginresponse_ = loginresponseBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom( com.google.protobuf.Message other )
            {
                if( other instanceof com.awar.ags.net.protocol.Protocol.ProtocolMSG )
                {
                    return mergeFrom( (com.awar.ags.net.protocol.Protocol.ProtocolMSG) other );
                }
                else
                {
                    super.mergeFrom( other );
                    return this;
                }
            }

            public Builder mergeFrom( com.awar.ags.net.protocol.Protocol.ProtocolMSG other )
            {
                if( other == com.awar.ags.net.protocol.Protocol.ProtocolMSG.getDefaultInstance() )
                {
                    return this;
                }
                if( other.hasLoginrequest() )
                {
                    mergeLoginrequest( other.getLoginrequest() );
                }
                if( other.hasLoginresponse() )
                {
                    mergeLoginresponse( other.getLoginresponse() );
                }
                this.mergeUnknownFields( other.getUnknownFields() );
                return this;
            }

            public final boolean isInitialized()
            {
                if( hasLoginrequest() )
                {
                    if( !getLoginrequest().isInitialized() )
                    {

                        return false;
                    }
                }
                if( hasLoginresponse() )
                {
                    if( !getLoginresponse().isInitialized() )
                    {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                    throws java.io.IOException
            {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields() );
                while( true )
                {
                    int tag = input.readTag();
                    switch( tag )
                    {
                        case 0:
                            this.setUnknownFields( unknownFields.build() );
                            onChanged();
                            return this;
                        default:
                        {
                            if( !parseUnknownField( input, unknownFields,
                                    extensionRegistry, tag ) )
                            {
                                this.setUnknownFields( unknownFields.build() );
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 26:
                        {
                            com.awar.ags.net.protocol.Protocol.LoginRequest.Builder subBuilder = com.awar.ags.net.protocol.Protocol.LoginRequest.newBuilder();
                            if( hasLoginrequest() )
                            {
                                subBuilder.mergeFrom( getLoginrequest() );
                            }
                            input.readMessage( subBuilder, extensionRegistry );
                            setLoginrequest( subBuilder.buildPartial() );
                            break;
                        }
                        case 34:
                        {
                            com.awar.ags.net.protocol.Protocol.LoginResponse.Builder subBuilder = com.awar.ags.net.protocol.Protocol.LoginResponse.newBuilder();
                            if( hasLoginresponse() )
                            {
                                subBuilder.mergeFrom( getLoginresponse() );
                            }
                            input.readMessage( subBuilder, extensionRegistry );
                            setLoginresponse( subBuilder.buildPartial() );
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional .com.awar.ags.net.protocol.LoginRequest loginrequest = 3;
            private com.awar.ags.net.protocol.Protocol.LoginRequest loginrequest_ = com.awar.ags.net.protocol.Protocol.LoginRequest.getDefaultInstance();
            private com.google.protobuf.SingleFieldBuilder<
                    com.awar.ags.net.protocol.Protocol.LoginRequest, com.awar.ags.net.protocol.Protocol.LoginRequest.Builder, com.awar.ags.net.protocol.Protocol.LoginRequestOrBuilder> loginrequestBuilder_;

            public boolean hasLoginrequest()
            {
                return ( ( bitField0_ & 0x00000001 ) == 0x00000001 );
            }

            public com.awar.ags.net.protocol.Protocol.LoginRequest getLoginrequest()
            {
                if( loginrequestBuilder_ == null )
                {
                    return loginrequest_;
                }
                else
                {
                    return loginrequestBuilder_.getMessage();
                }
            }

            public Builder setLoginrequest( com.awar.ags.net.protocol.Protocol.LoginRequest value )
            {
                if( loginrequestBuilder_ == null )
                {
                    if( value == null )
                    {
                        throw new NullPointerException();
                    }
                    loginrequest_ = value;
                    onChanged();
                }
                else
                {
                    loginrequestBuilder_.setMessage( value );
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            public Builder setLoginrequest(
                    com.awar.ags.net.protocol.Protocol.LoginRequest.Builder builderForValue )
            {
                if( loginrequestBuilder_ == null )
                {
                    loginrequest_ = builderForValue.build();
                    onChanged();
                }
                else
                {
                    loginrequestBuilder_.setMessage( builderForValue.build() );
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            public Builder mergeLoginrequest( com.awar.ags.net.protocol.Protocol.LoginRequest value )
            {
                if( loginrequestBuilder_ == null )
                {
                    if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) &&
                            loginrequest_ != com.awar.ags.net.protocol.Protocol.LoginRequest.getDefaultInstance() )
                    {
                        loginrequest_ =
                                com.awar.ags.net.protocol.Protocol.LoginRequest.newBuilder( loginrequest_ ).mergeFrom( value ).buildPartial();
                    }
                    else
                    {
                        loginrequest_ = value;
                    }
                    onChanged();
                }
                else
                {
                    loginrequestBuilder_.mergeFrom( value );
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            public Builder clearLoginrequest()
            {
                if( loginrequestBuilder_ == null )
                {
                    loginrequest_ = com.awar.ags.net.protocol.Protocol.LoginRequest.getDefaultInstance();
                    onChanged();
                }
                else
                {
                    loginrequestBuilder_.clear();
                }
                bitField0_ = ( bitField0_ & ~0x00000001 );
                return this;
            }

            public com.awar.ags.net.protocol.Protocol.LoginRequest.Builder getLoginrequestBuilder()
            {
                bitField0_ |= 0x00000001;
                onChanged();
                return getLoginrequestFieldBuilder().getBuilder();
            }

            public com.awar.ags.net.protocol.Protocol.LoginRequestOrBuilder getLoginrequestOrBuilder()
            {
                if( loginrequestBuilder_ != null )
                {
                    return loginrequestBuilder_.getMessageOrBuilder();
                }
                else
                {
                    return loginrequest_;
                }
            }

            private com.google.protobuf.SingleFieldBuilder<
                    com.awar.ags.net.protocol.Protocol.LoginRequest, com.awar.ags.net.protocol.Protocol.LoginRequest.Builder, com.awar.ags.net.protocol.Protocol.LoginRequestOrBuilder>
            getLoginrequestFieldBuilder()
            {
                if( loginrequestBuilder_ == null )
                {
                    loginrequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            com.awar.ags.net.protocol.Protocol.LoginRequest, com.awar.ags.net.protocol.Protocol.LoginRequest.Builder, com.awar.ags.net.protocol.Protocol.LoginRequestOrBuilder>(
                            loginrequest_,
                            getParentForChildren(),
                            isClean() );
                    loginrequest_ = null;
                }
                return loginrequestBuilder_;
            }

            // optional .com.awar.ags.net.protocol.LoginResponse loginresponse = 4;
            private com.awar.ags.net.protocol.Protocol.LoginResponse loginresponse_ = com.awar.ags.net.protocol.Protocol.LoginResponse.getDefaultInstance();
            private com.google.protobuf.SingleFieldBuilder<
                    com.awar.ags.net.protocol.Protocol.LoginResponse, com.awar.ags.net.protocol.Protocol.LoginResponse.Builder, com.awar.ags.net.protocol.Protocol.LoginResponseOrBuilder> loginresponseBuilder_;

            public boolean hasLoginresponse()
            {
                return ( ( bitField0_ & 0x00000002 ) == 0x00000002 );
            }

            public com.awar.ags.net.protocol.Protocol.LoginResponse getLoginresponse()
            {
                if( loginresponseBuilder_ == null )
                {
                    return loginresponse_;
                }
                else
                {
                    return loginresponseBuilder_.getMessage();
                }
            }

            public Builder setLoginresponse( com.awar.ags.net.protocol.Protocol.LoginResponse value )
            {
                if( loginresponseBuilder_ == null )
                {
                    if( value == null )
                    {
                        throw new NullPointerException();
                    }
                    loginresponse_ = value;
                    onChanged();
                }
                else
                {
                    loginresponseBuilder_.setMessage( value );
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            public Builder setLoginresponse(
                    com.awar.ags.net.protocol.Protocol.LoginResponse.Builder builderForValue )
            {
                if( loginresponseBuilder_ == null )
                {
                    loginresponse_ = builderForValue.build();
                    onChanged();
                }
                else
                {
                    loginresponseBuilder_.setMessage( builderForValue.build() );
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            public Builder mergeLoginresponse( com.awar.ags.net.protocol.Protocol.LoginResponse value )
            {
                if( loginresponseBuilder_ == null )
                {
                    if( ( ( bitField0_ & 0x00000002 ) == 0x00000002 ) &&
                            loginresponse_ != com.awar.ags.net.protocol.Protocol.LoginResponse.getDefaultInstance() )
                    {
                        loginresponse_ =
                                com.awar.ags.net.protocol.Protocol.LoginResponse.newBuilder( loginresponse_ ).mergeFrom( value ).buildPartial();
                    }
                    else
                    {
                        loginresponse_ = value;
                    }
                    onChanged();
                }
                else
                {
                    loginresponseBuilder_.mergeFrom( value );
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            public Builder clearLoginresponse()
            {
                if( loginresponseBuilder_ == null )
                {
                    loginresponse_ = com.awar.ags.net.protocol.Protocol.LoginResponse.getDefaultInstance();
                    onChanged();
                }
                else
                {
                    loginresponseBuilder_.clear();
                }
                bitField0_ = ( bitField0_ & ~0x00000002 );
                return this;
            }

            public com.awar.ags.net.protocol.Protocol.LoginResponse.Builder getLoginresponseBuilder()
            {
                bitField0_ |= 0x00000002;
                onChanged();
                return getLoginresponseFieldBuilder().getBuilder();
            }

            public com.awar.ags.net.protocol.Protocol.LoginResponseOrBuilder getLoginresponseOrBuilder()
            {
                if( loginresponseBuilder_ != null )
                {
                    return loginresponseBuilder_.getMessageOrBuilder();
                }
                else
                {
                    return loginresponse_;
                }
            }

            private com.google.protobuf.SingleFieldBuilder<
                    com.awar.ags.net.protocol.Protocol.LoginResponse, com.awar.ags.net.protocol.Protocol.LoginResponse.Builder, com.awar.ags.net.protocol.Protocol.LoginResponseOrBuilder>
            getLoginresponseFieldBuilder()
            {
                if( loginresponseBuilder_ == null )
                {
                    loginresponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            com.awar.ags.net.protocol.Protocol.LoginResponse, com.awar.ags.net.protocol.Protocol.LoginResponse.Builder, com.awar.ags.net.protocol.Protocol.LoginResponseOrBuilder>(
                            loginresponse_,
                            getParentForChildren(),
                            isClean() );
                    loginresponse_ = null;
                }
                return loginresponseBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:com.awar.ags.net.protocol.ProtocolMSG)
        }

        static
        {
            defaultInstance = new ProtocolMSG( true );
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.awar.ags.net.protocol.ProtocolMSG)
    }

    public interface LoginRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder
    {

        // required string login = 1;
        boolean hasLogin();

        String getLogin();
    }

    public static final class LoginRequest extends
            com.google.protobuf.GeneratedMessage
            implements LoginRequestOrBuilder
    {
        // Use LoginRequest.newBuilder() to construct.
        private LoginRequest( Builder builder )
        {
            super( builder );
        }

        private LoginRequest( boolean noInit )
        {
        }

        private static final LoginRequest defaultInstance;

        public static LoginRequest getDefaultInstance()
        {
            return defaultInstance;
        }

        public LoginRequest getDefaultInstanceForType()
        {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_LoginRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_LoginRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required string login = 1;
        public static final int LOGIN_FIELD_NUMBER = 1;
        private java.lang.Object login_;

        public boolean hasLogin()
        {
            return ( ( bitField0_ & 0x00000001 ) == 0x00000001 );
        }

        public String getLogin()
        {
            java.lang.Object ref = login_;
            if( ref instanceof String )
            {
                return (String) ref;
            }
            else
            {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if( com.google.protobuf.Internal.isValidUtf8( bs ) )
                {
                    login_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getLoginBytes()
        {
            java.lang.Object ref = login_;
            if( ref instanceof String )
            {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8( (String) ref );
                login_ = b;
                return b;
            }
            else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields()
        {
            login_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if( isInitialized != -1 )
            {
                return isInitialized == 1;
            }

            if( !hasLogin() )
            {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo( com.google.protobuf.CodedOutputStream output )
                throws java.io.IOException
        {
            getSerializedSize();
            if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) )
            {
                output.writeBytes( 1, getLoginBytes() );
            }
            getUnknownFields().writeTo( output );
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize()
        {
            int size = memoizedSerializedSize;
            if( size != -1 )
            {
                return size;
            }

            size = 0;
            if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) )
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize( 1, getLoginBytes() );
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException
        {
            return super.writeReplace();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseFrom(
                com.google.protobuf.ByteString data )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseFrom( byte[] data )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseFrom( java.io.InputStream input )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseDelimitedFrom( java.io.InputStream input )
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if( builder.mergeDelimitedFrom( input ) )
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if( builder.mergeDelimitedFrom( input, extensionRegistry ) )
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseFrom(
                com.google.protobuf.CodedInputStream input )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry )
                    .buildParsed();
        }

        public static Builder newBuilder()
        {
            return Builder.create();
        }

        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public static Builder newBuilder( com.awar.ags.net.protocol.Protocol.LoginRequest prototype )
        {
            return newBuilder().mergeFrom( prototype );
        }

        public Builder toBuilder()
        {
            return newBuilder( this );
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent )
        {
            Builder builder = new Builder( parent );
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.awar.ags.net.protocol.Protocol.LoginRequestOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_LoginRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_LoginRequest_fieldAccessorTable;
            }

            // Construct using com.awar.ags.net.protocol.Protocol.LoginRequest.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder( BuilderParent parent )
            {
                super( parent );
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization()
            {
                if( com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders )
                {
                }
            }

            private static Builder create()
            {
                return new Builder();
            }

            public Builder clear()
            {
                super.clear();
                login_ = "";
                bitField0_ = ( bitField0_ & ~0x00000001 );
                return this;
            }

            public Builder clone()
            {
                return create().mergeFrom( buildPartial() );
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return com.awar.ags.net.protocol.Protocol.LoginRequest.getDescriptor();
            }

            public com.awar.ags.net.protocol.Protocol.LoginRequest getDefaultInstanceForType()
            {
                return com.awar.ags.net.protocol.Protocol.LoginRequest.getDefaultInstance();
            }

            public com.awar.ags.net.protocol.Protocol.LoginRequest build()
            {
                com.awar.ags.net.protocol.Protocol.LoginRequest result = buildPartial();
                if( !result.isInitialized() )
                {
                    throw newUninitializedMessageException( result );
                }
                return result;
            }

            private com.awar.ags.net.protocol.Protocol.LoginRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                com.awar.ags.net.protocol.Protocol.LoginRequest result = buildPartial();
                if( !result.isInitialized() )
                {
                    throw newUninitializedMessageException(
                            result ).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.awar.ags.net.protocol.Protocol.LoginRequest buildPartial()
            {
                com.awar.ags.net.protocol.Protocol.LoginRequest result = new com.awar.ags.net.protocol.Protocol.LoginRequest( this );
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if( ( ( from_bitField0_ & 0x00000001 ) == 0x00000001 ) )
                {
                    to_bitField0_ |= 0x00000001;
                }
                result.login_ = login_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom( com.google.protobuf.Message other )
            {
                if( other instanceof com.awar.ags.net.protocol.Protocol.LoginRequest )
                {
                    return mergeFrom( (com.awar.ags.net.protocol.Protocol.LoginRequest) other );
                }
                else
                {
                    super.mergeFrom( other );
                    return this;
                }
            }

            public Builder mergeFrom( com.awar.ags.net.protocol.Protocol.LoginRequest other )
            {
                if( other == com.awar.ags.net.protocol.Protocol.LoginRequest.getDefaultInstance() )
                {
                    return this;
                }
                if( other.hasLogin() )
                {
                    setLogin( other.getLogin() );
                }
                this.mergeUnknownFields( other.getUnknownFields() );
                return this;
            }

            public final boolean isInitialized()
            {
                if( !hasLogin() )
                {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                    throws java.io.IOException
            {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields() );
                while( true )
                {
                    int tag = input.readTag();
                    switch( tag )
                    {
                        case 0:
                            this.setUnknownFields( unknownFields.build() );
                            onChanged();
                            return this;
                        default:
                        {
                            if( !parseUnknownField( input, unknownFields,
                                    extensionRegistry, tag ) )
                            {
                                this.setUnknownFields( unknownFields.build() );
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10:
                        {
                            bitField0_ |= 0x00000001;
                            login_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string login = 1;
            private java.lang.Object login_ = "";

            public boolean hasLogin()
            {
                return ( ( bitField0_ & 0x00000001 ) == 0x00000001 );
            }

            public String getLogin()
            {
                java.lang.Object ref = login_;
                if( !( ref instanceof String ) )
                {
                    String s = ( (com.google.protobuf.ByteString) ref ).toStringUtf8();
                    login_ = s;
                    return s;
                }
                else
                {
                    return (String) ref;
                }
            }

            public Builder setLogin( String value )
            {
                if( value == null )
                {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                login_ = value;
                onChanged();
                return this;
            }

            public Builder clearLogin()
            {
                bitField0_ = ( bitField0_ & ~0x00000001 );
                login_ = getDefaultInstance().getLogin();
                onChanged();
                return this;
            }

            void setLogin( com.google.protobuf.ByteString value )
            {
                bitField0_ |= 0x00000001;
                login_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:com.awar.ags.net.protocol.LoginRequest)
        }

        static
        {
            defaultInstance = new LoginRequest( true );
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.awar.ags.net.protocol.LoginRequest)
    }

    public interface LoginResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder
    {

        // required int32 idsess = 1;
        boolean hasIdsess();

        int getIdsess();

        // required int32 idplay = 2;
        boolean hasIdplay();

        int getIdplay();
    }

    public static final class LoginResponse extends
            com.google.protobuf.GeneratedMessage
            implements LoginResponseOrBuilder
    {
        // Use LoginResponse.newBuilder() to construct.
        private LoginResponse( Builder builder )
        {
            super( builder );
        }

        private LoginResponse( boolean noInit )
        {
        }

        private static final LoginResponse defaultInstance;

        public static LoginResponse getDefaultInstance()
        {
            return defaultInstance;
        }

        public LoginResponse getDefaultInstanceForType()
        {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_LoginResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_LoginResponse_fieldAccessorTable;
        }

        private int bitField0_;
        // required int32 idsess = 1;
        public static final int IDSESS_FIELD_NUMBER = 1;
        private int idsess_;

        public boolean hasIdsess()
        {
            return ( ( bitField0_ & 0x00000001 ) == 0x00000001 );
        }

        public int getIdsess()
        {
            return idsess_;
        }

        // required int32 idplay = 2;
        public static final int IDPLAY_FIELD_NUMBER = 2;
        private int idplay_;

        public boolean hasIdplay()
        {
            return ( ( bitField0_ & 0x00000002 ) == 0x00000002 );
        }

        public int getIdplay()
        {
            return idplay_;
        }

        private void initFields()
        {
            idsess_ = 0;
            idplay_ = 0;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if( isInitialized != -1 )
            {
                return isInitialized == 1;
            }

            if( !hasIdsess() )
            {
                memoizedIsInitialized = 0;
                return false;
            }
            if( !hasIdplay() )
            {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo( com.google.protobuf.CodedOutputStream output )
                throws java.io.IOException
        {
            getSerializedSize();
            if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) )
            {
                output.writeInt32( 1, idsess_ );
            }
            if( ( ( bitField0_ & 0x00000002 ) == 0x00000002 ) )
            {
                output.writeInt32( 2, idplay_ );
            }
            getUnknownFields().writeTo( output );
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize()
        {
            int size = memoizedSerializedSize;
            if( size != -1 )
            {
                return size;
            }

            size = 0;
            if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) )
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size( 1, idsess_ );
            }
            if( ( ( bitField0_ & 0x00000002 ) == 0x00000002 ) )
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size( 2, idplay_ );
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException
        {
            return super.writeReplace();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseFrom(
                com.google.protobuf.ByteString data )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseFrom( byte[] data )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseFrom( java.io.InputStream input )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseDelimitedFrom( java.io.InputStream input )
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if( builder.mergeDelimitedFrom( input ) )
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if( builder.mergeDelimitedFrom( input, extensionRegistry ) )
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseFrom(
                com.google.protobuf.CodedInputStream input )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.LoginResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry )
                    .buildParsed();
        }

        public static Builder newBuilder()
        {
            return Builder.create();
        }

        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public static Builder newBuilder( com.awar.ags.net.protocol.Protocol.LoginResponse prototype )
        {
            return newBuilder().mergeFrom( prototype );
        }

        public Builder toBuilder()
        {
            return newBuilder( this );
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent )
        {
            Builder builder = new Builder( parent );
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.awar.ags.net.protocol.Protocol.LoginResponseOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_LoginResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_LoginResponse_fieldAccessorTable;
            }

            // Construct using com.awar.ags.net.protocol.Protocol.LoginResponse.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder( BuilderParent parent )
            {
                super( parent );
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization()
            {
                if( com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders )
                {
                }
            }

            private static Builder create()
            {
                return new Builder();
            }

            public Builder clear()
            {
                super.clear();
                idsess_ = 0;
                bitField0_ = ( bitField0_ & ~0x00000001 );
                idplay_ = 0;
                bitField0_ = ( bitField0_ & ~0x00000002 );
                return this;
            }

            public Builder clone()
            {
                return create().mergeFrom( buildPartial() );
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return com.awar.ags.net.protocol.Protocol.LoginResponse.getDescriptor();
            }

            public com.awar.ags.net.protocol.Protocol.LoginResponse getDefaultInstanceForType()
            {
                return com.awar.ags.net.protocol.Protocol.LoginResponse.getDefaultInstance();
            }

            public com.awar.ags.net.protocol.Protocol.LoginResponse build()
            {
                com.awar.ags.net.protocol.Protocol.LoginResponse result = buildPartial();
                if( !result.isInitialized() )
                {
                    throw newUninitializedMessageException( result );
                }
                return result;
            }

            private com.awar.ags.net.protocol.Protocol.LoginResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                com.awar.ags.net.protocol.Protocol.LoginResponse result = buildPartial();
                if( !result.isInitialized() )
                {
                    throw newUninitializedMessageException(
                            result ).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.awar.ags.net.protocol.Protocol.LoginResponse buildPartial()
            {
                com.awar.ags.net.protocol.Protocol.LoginResponse result = new com.awar.ags.net.protocol.Protocol.LoginResponse( this );
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if( ( ( from_bitField0_ & 0x00000001 ) == 0x00000001 ) )
                {
                    to_bitField0_ |= 0x00000001;
                }
                result.idsess_ = idsess_;
                if( ( ( from_bitField0_ & 0x00000002 ) == 0x00000002 ) )
                {
                    to_bitField0_ |= 0x00000002;
                }
                result.idplay_ = idplay_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom( com.google.protobuf.Message other )
            {
                if( other instanceof com.awar.ags.net.protocol.Protocol.LoginResponse )
                {
                    return mergeFrom( (com.awar.ags.net.protocol.Protocol.LoginResponse) other );
                }
                else
                {
                    super.mergeFrom( other );
                    return this;
                }
            }

            public Builder mergeFrom( com.awar.ags.net.protocol.Protocol.LoginResponse other )
            {
                if( other == com.awar.ags.net.protocol.Protocol.LoginResponse.getDefaultInstance() )
                {
                    return this;
                }
                if( other.hasIdsess() )
                {
                    setIdsess( other.getIdsess() );
                }
                if( other.hasIdplay() )
                {
                    setIdplay( other.getIdplay() );
                }
                this.mergeUnknownFields( other.getUnknownFields() );
                return this;
            }

            public final boolean isInitialized()
            {
                if( !hasIdsess() )
                {

                    return false;
                }
                if( !hasIdplay() )
                {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                    throws java.io.IOException
            {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields() );
                while( true )
                {
                    int tag = input.readTag();
                    switch( tag )
                    {
                        case 0:
                            this.setUnknownFields( unknownFields.build() );
                            onChanged();
                            return this;
                        default:
                        {
                            if( !parseUnknownField( input, unknownFields,
                                    extensionRegistry, tag ) )
                            {
                                this.setUnknownFields( unknownFields.build() );
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8:
                        {
                            bitField0_ |= 0x00000001;
                            idsess_ = input.readInt32();
                            break;
                        }
                        case 16:
                        {
                            bitField0_ |= 0x00000002;
                            idplay_ = input.readInt32();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required int32 idsess = 1;
            private int idsess_;

            public boolean hasIdsess()
            {
                return ( ( bitField0_ & 0x00000001 ) == 0x00000001 );
            }

            public int getIdsess()
            {
                return idsess_;
            }

            public Builder setIdsess( int value )
            {
                bitField0_ |= 0x00000001;
                idsess_ = value;
                onChanged();
                return this;
            }

            public Builder clearIdsess()
            {
                bitField0_ = ( bitField0_ & ~0x00000001 );
                idsess_ = 0;
                onChanged();
                return this;
            }

            // required int32 idplay = 2;
            private int idplay_;

            public boolean hasIdplay()
            {
                return ( ( bitField0_ & 0x00000002 ) == 0x00000002 );
            }

            public int getIdplay()
            {
                return idplay_;
            }

            public Builder setIdplay( int value )
            {
                bitField0_ |= 0x00000002;
                idplay_ = value;
                onChanged();
                return this;
            }

            public Builder clearIdplay()
            {
                bitField0_ = ( bitField0_ & ~0x00000002 );
                idplay_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.awar.ags.net.protocol.LoginResponse)
        }

        static
        {
            defaultInstance = new LoginResponse( true );
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.awar.ags.net.protocol.LoginResponse)
    }

    public interface MoveRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder
    {

        // required int32 x = 1;
        boolean hasX();

        int getX();

        // required int32 y = 2;
        boolean hasY();

        int getY();
    }

    public static final class MoveRequest extends
            com.google.protobuf.GeneratedMessage
            implements MoveRequestOrBuilder
    {
        // Use MoveRequest.newBuilder() to construct.
        private MoveRequest( Builder builder )
        {
            super( builder );
        }

        private MoveRequest( boolean noInit )
        {
        }

        private static final MoveRequest defaultInstance;

        public static MoveRequest getDefaultInstance()
        {
            return defaultInstance;
        }

        public MoveRequest getDefaultInstanceForType()
        {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_MoveRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_MoveRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required int32 x = 1;
        public static final int X_FIELD_NUMBER = 1;
        private int x_;

        public boolean hasX()
        {
            return ( ( bitField0_ & 0x00000001 ) == 0x00000001 );
        }

        public int getX()
        {
            return x_;
        }

        // required int32 y = 2;
        public static final int Y_FIELD_NUMBER = 2;
        private int y_;

        public boolean hasY()
        {
            return ( ( bitField0_ & 0x00000002 ) == 0x00000002 );
        }

        public int getY()
        {
            return y_;
        }

        private void initFields()
        {
            x_ = 0;
            y_ = 0;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if( isInitialized != -1 )
            {
                return isInitialized == 1;
            }

            if( !hasX() )
            {
                memoizedIsInitialized = 0;
                return false;
            }
            if( !hasY() )
            {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo( com.google.protobuf.CodedOutputStream output )
                throws java.io.IOException
        {
            getSerializedSize();
            if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) )
            {
                output.writeInt32( 1, x_ );
            }
            if( ( ( bitField0_ & 0x00000002 ) == 0x00000002 ) )
            {
                output.writeInt32( 2, y_ );
            }
            getUnknownFields().writeTo( output );
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize()
        {
            int size = memoizedSerializedSize;
            if( size != -1 )
            {
                return size;
            }

            size = 0;
            if( ( ( bitField0_ & 0x00000001 ) == 0x00000001 ) )
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size( 1, x_ );
            }
            if( ( ( bitField0_ & 0x00000002 ) == 0x00000002 ) )
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size( 2, y_ );
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException
        {
            return super.writeReplace();
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseFrom(
                com.google.protobuf.ByteString data )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseFrom( byte[] data )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseFrom( java.io.InputStream input )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry )
                    .buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseDelimitedFrom( java.io.InputStream input )
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if( builder.mergeDelimitedFrom( input ) )
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if( builder.mergeDelimitedFrom( input, extensionRegistry ) )
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseFrom(
                com.google.protobuf.CodedInputStream input )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.awar.ags.net.protocol.Protocol.MoveRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry )
                    .buildParsed();
        }

        public static Builder newBuilder()
        {
            return Builder.create();
        }

        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public static Builder newBuilder( com.awar.ags.net.protocol.Protocol.MoveRequest prototype )
        {
            return newBuilder().mergeFrom( prototype );
        }

        public Builder toBuilder()
        {
            return newBuilder( this );
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent )
        {
            Builder builder = new Builder( parent );
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.awar.ags.net.protocol.Protocol.MoveRequestOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_MoveRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return com.awar.ags.net.protocol.Protocol.internal_static_com_awar_ags_net_protocol_MoveRequest_fieldAccessorTable;
            }

            // Construct using com.awar.ags.net.protocol.Protocol.MoveRequest.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder( BuilderParent parent )
            {
                super( parent );
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization()
            {
                if( com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders )
                {
                }
            }

            private static Builder create()
            {
                return new Builder();
            }

            public Builder clear()
            {
                super.clear();
                x_ = 0;
                bitField0_ = ( bitField0_ & ~0x00000001 );
                y_ = 0;
                bitField0_ = ( bitField0_ & ~0x00000002 );
                return this;
            }

            public Builder clone()
            {
                return create().mergeFrom( buildPartial() );
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return com.awar.ags.net.protocol.Protocol.MoveRequest.getDescriptor();
            }

            public com.awar.ags.net.protocol.Protocol.MoveRequest getDefaultInstanceForType()
            {
                return com.awar.ags.net.protocol.Protocol.MoveRequest.getDefaultInstance();
            }

            public com.awar.ags.net.protocol.Protocol.MoveRequest build()
            {
                com.awar.ags.net.protocol.Protocol.MoveRequest result = buildPartial();
                if( !result.isInitialized() )
                {
                    throw newUninitializedMessageException( result );
                }
                return result;
            }

            private com.awar.ags.net.protocol.Protocol.MoveRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                com.awar.ags.net.protocol.Protocol.MoveRequest result = buildPartial();
                if( !result.isInitialized() )
                {
                    throw newUninitializedMessageException(
                            result ).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.awar.ags.net.protocol.Protocol.MoveRequest buildPartial()
            {
                com.awar.ags.net.protocol.Protocol.MoveRequest result = new com.awar.ags.net.protocol.Protocol.MoveRequest( this );
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if( ( ( from_bitField0_ & 0x00000001 ) == 0x00000001 ) )
                {
                    to_bitField0_ |= 0x00000001;
                }
                result.x_ = x_;
                if( ( ( from_bitField0_ & 0x00000002 ) == 0x00000002 ) )
                {
                    to_bitField0_ |= 0x00000002;
                }
                result.y_ = y_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom( com.google.protobuf.Message other )
            {
                if( other instanceof com.awar.ags.net.protocol.Protocol.MoveRequest )
                {
                    return mergeFrom( (com.awar.ags.net.protocol.Protocol.MoveRequest) other );
                }
                else
                {
                    super.mergeFrom( other );
                    return this;
                }
            }

            public Builder mergeFrom( com.awar.ags.net.protocol.Protocol.MoveRequest other )
            {
                if( other == com.awar.ags.net.protocol.Protocol.MoveRequest.getDefaultInstance() )
                {
                    return this;
                }
                if( other.hasX() )
                {
                    setX( other.getX() );
                }
                if( other.hasY() )
                {
                    setY( other.getY() );
                }
                this.mergeUnknownFields( other.getUnknownFields() );
                return this;
            }

            public final boolean isInitialized()
            {
                if( !hasX() )
                {

                    return false;
                }
                if( !hasY() )
                {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry )
                    throws java.io.IOException
            {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields() );
                while( true )
                {
                    int tag = input.readTag();
                    switch( tag )
                    {
                        case 0:
                            this.setUnknownFields( unknownFields.build() );
                            onChanged();
                            return this;
                        default:
                        {
                            if( !parseUnknownField( input, unknownFields,
                                    extensionRegistry, tag ) )
                            {
                                this.setUnknownFields( unknownFields.build() );
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8:
                        {
                            bitField0_ |= 0x00000001;
                            x_ = input.readInt32();
                            break;
                        }
                        case 16:
                        {
                            bitField0_ |= 0x00000002;
                            y_ = input.readInt32();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required int32 x = 1;
            private int x_;

            public boolean hasX()
            {
                return ( ( bitField0_ & 0x00000001 ) == 0x00000001 );
            }

            public int getX()
            {
                return x_;
            }

            public Builder setX( int value )
            {
                bitField0_ |= 0x00000001;
                x_ = value;
                onChanged();
                return this;
            }

            public Builder clearX()
            {
                bitField0_ = ( bitField0_ & ~0x00000001 );
                x_ = 0;
                onChanged();
                return this;
            }

            // required int32 y = 2;
            private int y_;

            public boolean hasY()
            {
                return ( ( bitField0_ & 0x00000002 ) == 0x00000002 );
            }

            public int getY()
            {
                return y_;
            }

            public Builder setY( int value )
            {
                bitField0_ |= 0x00000002;
                y_ = value;
                onChanged();
                return this;
            }

            public Builder clearY()
            {
                bitField0_ = ( bitField0_ & ~0x00000002 );
                y_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.awar.ags.net.protocol.MoveRequest)
        }

        static
        {
            defaultInstance = new MoveRequest( true );
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.awar.ags.net.protocol.MoveRequest)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_com_awar_ags_net_protocol_ProtocolMSG_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_awar_ags_net_protocol_ProtocolMSG_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_com_awar_ags_net_protocol_LoginRequest_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_awar_ags_net_protocol_LoginRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_com_awar_ags_net_protocol_LoginResponse_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_awar_ags_net_protocol_LoginResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_com_awar_ags_net_protocol_MoveRequest_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_awar_ags_net_protocol_MoveRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor()
    {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static
    {
        java.lang.String[] descriptorData = {
                "\n\016protocol.proto\022\031com.awar.ags.net.proto" +
                        "col\"\215\001\n\013ProtocolMSG\022=\n\014loginrequest\030\003 \001(" +
                        "\0132\'.com.awar.ags.net.protocol.LoginReque" +
                        "st\022?\n\rloginresponse\030\004 \001(\0132(.com.awar.ags" +
                        ".net.protocol.LoginResponse\"\035\n\014LoginRequ" +
                        "est\022\r\n\005login\030\001 \002(\t\"/\n\rLoginResponse\022\016\n\006i" +
                        "dsess\030\001 \002(\005\022\016\n\006idplay\030\002 \002(\005\"#\n\013MoveReque" +
                        "st\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005B%\n\031com.awar.ags" +
                        ".net.protocolB\010Protocol"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner()
                {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root )
                    {
                        descriptor = root;
                        internal_static_com_awar_ags_net_protocol_ProtocolMSG_descriptor =
                                getDescriptor().getMessageTypes().get( 0 );
                        internal_static_com_awar_ags_net_protocol_ProtocolMSG_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_awar_ags_net_protocol_ProtocolMSG_descriptor,
                                new java.lang.String[]{ "Loginrequest", "Loginresponse", },
                                com.awar.ags.net.protocol.Protocol.ProtocolMSG.class,
                                com.awar.ags.net.protocol.Protocol.ProtocolMSG.Builder.class );
                        internal_static_com_awar_ags_net_protocol_LoginRequest_descriptor =
                                getDescriptor().getMessageTypes().get( 1 );
                        internal_static_com_awar_ags_net_protocol_LoginRequest_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_awar_ags_net_protocol_LoginRequest_descriptor,
                                new java.lang.String[]{ "Login", },
                                com.awar.ags.net.protocol.Protocol.LoginRequest.class,
                                com.awar.ags.net.protocol.Protocol.LoginRequest.Builder.class );
                        internal_static_com_awar_ags_net_protocol_LoginResponse_descriptor =
                                getDescriptor().getMessageTypes().get( 2 );
                        internal_static_com_awar_ags_net_protocol_LoginResponse_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_awar_ags_net_protocol_LoginResponse_descriptor,
                                new java.lang.String[]{ "Idsess", "Idplay", },
                                com.awar.ags.net.protocol.Protocol.LoginResponse.class,
                                com.awar.ags.net.protocol.Protocol.LoginResponse.Builder.class );
                        internal_static_com_awar_ags_net_protocol_MoveRequest_descriptor =
                                getDescriptor().getMessageTypes().get( 3 );
                        internal_static_com_awar_ags_net_protocol_MoveRequest_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_awar_ags_net_protocol_MoveRequest_descriptor,
                                new java.lang.String[]{ "X", "Y", },
                                com.awar.ags.net.protocol.Protocol.MoveRequest.class,
                                com.awar.ags.net.protocol.Protocol.MoveRequest.Builder.class );
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom( descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner );
    }

    // @@protoc_insertion_point(outer_class_scope)
}
